apiVersion: v1
kind: Service
metadata:
  name: {{ include "instance-automation.fullname" . }}-metrics
  labels:
    {{- include "instance-automation.labels" . | nindent 4 }}
    {{- include "instance-automation.metricsAdditionalLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "instance-automation.selectorLabels" . | nindent 4 }}
