apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "instance-operator.fullname" . }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCountOperator }}
  selector:
    matchLabels:
      {{- include "instance-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "instance-operator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "instance-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext.operator | nindent 12 }}
          image: "{{ .Values.image.repositoryOperator }}:{{ include "instance-operator.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--namespace-whitelist={{ .Values.configurations.generic.whitelistLabels }}"
            - "--website-base-url={{ .Values.configurations.generic.websiteBaseUrl }}"
            - "--instances-auth-url={{ .Values.configurations.generic.instancesAuthUrl }}"
            - "--container-env-sidecars-tag={{ include "instance-operator.containerEnvironmentSidecarsTag" . }}"
            - "--container-env-x-vnc-img={{ .Values.configurations.containerEnvironmentOptions.xVncImage }}"
            - "--container-env-websockify-img={{ .Values.configurations.containerEnvironmentOptions.websockifyImage }}"
            - "--container-env-content-downloader-img={{ .Values.configurations.containerEnvironmentOptions.contentDownloaderImage }}"
            - "--container-env-content-uploader-img={{ .Values.configurations.containerEnvironmentOptions.contentUploaderImage }}"
            - "--container-env-instmetrics-server-endpoint={{ .Values.configurations.containerEnvironmentOptions.instmetricsServerEndpoint }}"
            - "--vm-registry={{ .Values.configurations.privateContainerRegistry.url }}"
            - "--vm-registry-secret={{ .Values.configurations.privateContainerRegistry.secretName }}"
            - "--container-export-img={{ .Values.configurations.containerVmSnapshots.exportImage }}:{{ include "instance-operator.containerExportImageTag" . }}"
            - "--container-kaniko-img={{ .Values.configurations.containerVmSnapshots.kanikoImage }}"
            - "--max-concurrent-reconciles={{ .Values.configurations.maxConcurrentReconciles }}"
          ports:
            - name: op-metrics
              containerPort: 8080
              protocol: TCP
            - name: op-probes
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: op-probes
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: op-probes
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources.operator | nindent 12 }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "instance-operator.selectorLabels" . | nindent 18 }}
                  app.kubernetes.io/component: operator
              topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "instance-operator.fullname" . }}-automation
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: automation
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCountAutomation }}
  selector:
    matchLabels:
      {{- include "instance-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: automation
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "instance-operator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: automation
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "instance-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}-automation
          securityContext:
            {{- toYaml .Values.securityContext.automation | nindent 12 }}
          image: "{{ .Values.image.repositoryAutomation }}:{{ include "instance-operator.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--enable-instance-termination={{ .Values.configurations.automation.enableInstanceTermination }}"
            - "--enable-instance-inactive-termination={{ .Values.configurations.automation.enableInstanceInactiveTermination }}"
            - "--enable-instance-submission={{ .Values.configurations.automation.enableInstanceSubmission }}"
            - "--enable-instance-expiration={{ .Values.configurations.automation.enableInstanceExpiration }}"
            - "--namespace-whitelist={{ .Values.configurations.generic.whitelistLabels }}"
            - "--container-env-sidecars-tag={{ include "instance-operator.containerEnvironmentSidecarsTag" . }}"
            - "--container-env-content-uploader-img={{ .Values.configurations.containerEnvironmentOptions.contentUploaderImage }}"
            - "--monitoring-prometheus-url={{ .Values.configurations.monitoring.prometheusURL }}"
            - "--max-concurrent-reconciles-termination={{ .Values.configurations.automation.maxConcurrentTerminationReconciles }}"
            - "--max-concurrent-reconciles-inactive-termination={{ .Values.configurations.automation.maxConcurrentInactiveTerminationReconciles }}"
            - "--max-concurrent-reconciles-submission={{ .Values.configurations.automation.maxConcurrentSubmissionReconciles }}"
            - "--instance-termination-status-check-timeout={{ .Values.configurations.automation.terminationStatusCheckTimeout }}"
            - "--instance-termination-status-check-interval={{ .Values.configurations.automation.terminationStatusCheckInterval }}"
            - "--instance-inactive-termination-status-check-timeout={{ .Values.configurations.automation.inactiveTerminationStatusCheckTimeout }}"
            - "--instance-inactive-termination-max-number-of-alerts={{.Values.configurations.automation.inactiveTerminationMaxNumberOfAlerts}}" 
            - "--smtp-server={{ .Values.configurations.smtp.server }}"
            - "--smtp-port={{ .Values.configurations.smtp.port }}"
            - "--smtp-identity={{ .Values.configurations.smtp.identity }}"
            - "--smtp-username={{ .Values.configurations.smtp.username }}"
            - "--smtp-password={{ .Values.configurations.smtp.password }}"
            - "--smtp-from={{ .Values.configurations.smtp.from }}"
          ports:
            - name: auto-metrics
              containerPort: 8080
              protocol: TCP
            - name: auto-probes
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: auto-probes
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: auto-probes
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources.automation | nindent 12 }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "instance-operator.selectorLabels" . | nindent 18 }}
                  app.kubernetes.io/component: automation
              topologyKey: kubernetes.io/hostname
