# Default values for crownlabs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  version: "" # default set while packaging

createClusterRoles: true

frontend-app:
  replicaCount: 1
  image:
    repository: crownlabs/frontend-app
  ingress:
    hostname: crownlabs.example.com
    path: /
  configuration:
    backend:
      graphql: https://graphql.example.com
    oidc:
      clientId: <client-id>
      providerUrl: https://auth.example.com/auth/

qlkube:
  replicaCount: 1
  image:
    repository: crownlabs/qlkube
  rbacResourcesName: crownlabs-qlkube
  ingress:
    hostname: qlkube.crownlabs.example.com
  harborToken: {}
  configuration:
    exposedAPIs:
      apis:
        - crownlabs.polito.it
    subscriptions:
      apis:
        - group: crownlabs.polito.it
          resources:
            - resource: instances
              version: v1alpha2
              mapping: itPolitoCrownlabsV1alpha2Instance
              listMapping: itPolitoCrownlabsV1alpha2InstanceList
            - resource: templates
              version: v1alpha2
              mapping: itPolitoCrownlabsV1alpha2Template
    wrappers:
      fileName: wrappers.js
      resources:
        - type: itPolitoCrownlabsV1alpha2Template
          fieldWrapper: TemplateCrownlabsPolitoItTemplateRef
          nameWrapper: templateWrapper
          queryFieldsRequired:
            - name
            - namespace
          parents:
            - itPolitoCrownlabsV1alpha2Instance

instance-operator:
  replicaCount: 1
  image:
    repository: crownlabs/instance-operator
  rbacResourcesName: crownlabs-instance-operator
  configurations:
    mailConfigMapName: crownlabs-mail-config
    generic:
      whitelistLabels: crownlabs.polito.it/operator-selector=production
      websiteBaseUrl: crownlabs.example.com
      instancesAuthUrl: https://crownlabs.example.com/auth
    containerEnvironmentOptions:
      tag: ""
      websockifyImage: crownlabs/websockify
      vncImage: crownlabs/tigervnc
      contentDownloaderImage: crownlabs/content-downloader
      contentUploaderImage: crownlabs/content-uploader
      instmetricsServerEndpoint: crownlabs-instmetrics.crownlabs-production:9090
    containerVmSnapshots:
      kanikoImage: gcr.io/kaniko-project/executor
      exportImage: "crownlabs/img-exporter"
      exportImageTag: ""
    privateContainerRegistry:
      url: registry.crownlabs.example.com
      secretName: registry-credentials
    maxConcurrentReconciles: 1
    maxAutomationConcurrentReconciles: 1
    monitoring:
      prometheusURL: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
      queryNginxAvailable: count(up{service="ingress-nginx-external-controller-metrics"})
      queryBastionSSHAvailable: count(up{container="bastion-operator-tracker-sidecar"})
      queryNginxData: nginx_ingress_controller_requests{exported_namespace="%s", exported_service="%s"}
      queryBastionSSHData: bastion_ssh_connections{destination_ip="%s"}
    automation:
      enableInstanceSubmission: true
      enableInstanceTermination: true
      enableInstanceInactiveTermination: true
      enableInstanceExpiration: true
      maxConcurrentTerminationReconciles: 1
      maxConcurrentInactiveTerminationReconciles: 1
      maxConcurrentSubmissionReconciles: 1
      terminationStatusCheckTimeout: "3s"
      terminationStatusCheckInterval: "2m" 
      inactiveTerminationStatusCheckTimeout: "3s"
      inactiveTerminationMaxNumberOfAlerts: 3
      enableInactivityNotifications: true
      enableExpirationNotifications: true
      notificationInterval: "24h"

tenant-operator:
  replicaCount: 1
  image:
    repository: crownlabs/tenant-operator
  rbacResourcesName: crownlabs-tenant-operator
  configurations:
    targetLabel: crownlabs.polito.it/operator-selector=production
    keycloak:
      url: "https://auth.crownlabs.example.com/"
      loginRealm: master
      targetRealm: crownlabs
      targetClient: k8s
      user: username
      pass: password
    maxConcurrentReconciles: 1
    tenantNamespaceKeepAlive: 168h
  webhook:
    deployment:
      webhookBypassGroups: system:masters,system:serviceaccounts,kubernetes:admin
      baseWorkspaces: utilities
    enableMutating: true

bastion-operator:
  replicaCount: 1
  image:
    repositoryBastion: crownlabs/ssh-bastion
    repositorySidecar: crownlabs/bastion-operator
  rbacResourcesName: crownlabs-bastion-operator
  serviceAnnotations: {}
  service:
    type: LoadBalancer
    port: 22
    externalTrafficPolicy: Cluster

image-list:
  replicaCount: 1
  image:
    repository: crownlabs/crownlabs-image-list
  rbacResourcesName: crownlabs-image-list
  configurations:
    registryUrl: http://docker-registry.docker-registry:5000
    advRegistryName: registry.crownlabs.example.com
    imageListName: crownlabs-virtual-machine-images
    updateInterval: 60

exam-agent:
  replicaCount: 1
  configurations:
    allowedIPs: ""
    targetNamespace: "crownlabs-exam"
  exposition:
    host: exams.crownlabs.polito.it
    basePath: "/api"
  image:
    repository: crownlabs/exam-agent
    pullPolicy: IfNotPresent

instmetrics:
  image:
    repository: crownlabs/instmetrics
  configurations:
    runtimeEndpoint: unix:///run/dockershim.sock
    containerRuntime: /run/dockershim.sock
    dockerSocket: /var/run/docker.sock
    connectionTimeout:  10s
    updatePeriod: 4s
    grpcPort: 9090

policies:
  ingressHostnamePattern: s??????.sandbox.crownlabs.polito.it
  namespaceSelector:
    matchExpressions:
      - key: crownlabs.polito.it/type
        operator: In
        values:
        - sandbox
